# Generated by Django 3.1.1 on 2020-09-14 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User_db',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('role', models.CharField(default='user', max_length=100)),
                ('mobile', models.CharField(max_length=10)),
                ('email', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=300)),
                ('address', models.CharField(max_length=300)),
                ('photo', models.ImageField(blank=True, default='profile/def.png', null=True, upload_to='profile/')),
                ('time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
