# Generated by Django 3.1.1 on 2020-09-23 10:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Banners',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('desc', models.CharField(max_length=500, null=True)),
                ('alt', models.CharField(default='banner image', max_length=100)),
                ('category', models.CharField(default='uncategorized', max_length=100)),
                ('photo', models.ImageField(upload_to='banner/')),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Pages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('meta', models.CharField(max_length=500)),
                ('slug', models.CharField(max_length=500)),
                ('keywords', models.CharField(max_length=300)),
                ('post', models.CharField(max_length=3000)),
                ('body_photo', models.ImageField(blank=True, null=True, upload_to='page/')),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='User_db',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('role', models.CharField(default='user', max_length=100)),
                ('mobile', models.CharField(max_length=10)),
                ('email', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=300)),
                ('address', models.CharField(max_length=300)),
                ('photo', models.ImageField(blank=True, default='profile/def.png', null=True, upload_to='profile/')),
                ('time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Posts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('meta', models.CharField(max_length=500)),
                ('slug', models.CharField(max_length=500)),
                ('keywords', models.CharField(max_length=300)),
                ('post', models.CharField(max_length=3000)),
                ('banner_photo', models.ImageField(blank=True, default='post/def.jpg', null=True, upload_to='post/')),
                ('body_photo', models.ImageField(blank=True, null=True, upload_to='post/')),
                ('pub_date', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tasks.user_db')),
            ],
            options={
                'ordering': ['title'],
            },
        ),
    ]
