# Generated by Django 3.1.1 on 2020-12-18 06:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='super_plan_forms',
            name='capex_years',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='capex_years', to='tasks.super_plan_forms_multiple_inputs'),
        ),
        migrations.AddField(
            model_name='super_plan_forms',
            name='current_assets_years',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='current_assets_years', to='tasks.super_plan_forms_multiple_inputs'),
        ),
        migrations.AddField(
            model_name='super_plan_forms',
            name='current_liabilities_years',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='current_liabilities_years', to='tasks.super_plan_forms_multiple_inputs'),
        ),
        migrations.AddField(
            model_name='super_plan_forms',
            name='non_current_assets_years',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='non_current_assets_years', to='tasks.super_plan_forms_multiple_inputs'),
        ),
        migrations.AddField(
            model_name='super_plan_forms',
            name='non_current_liabilities_years',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='non_current_liabilities_years', to='tasks.super_plan_forms_multiple_inputs'),
        ),
        migrations.AddField(
            model_name='super_plan_forms',
            name='operating_expenses_growth_or_amount_years',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='operating_expenses_growth_or_amount_years', to='tasks.super_plan_forms_multiple_inputs'),
        ),
        migrations.AddField(
            model_name='super_plan_forms',
            name='revenue_growth_or_amount_years',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='revenue_growth_or_amount_years', to='tasks.super_plan_forms_multiple_inputs'),
        ),
        migrations.AddField(
            model_name='super_plan_forms',
            name='share_capital_years',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='share_capital_years', to='tasks.super_plan_forms_multiple_inputs'),
        ),
    ]
