# Generated by Django 3.1.1 on 2020-09-16 03:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Posts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('meta', models.CharField(max_length=500)),
                ('slug', models.CharField(max_length=500)),
                ('keywords', models.CharField(max_length=300)),
                ('post', models.CharField(max_length=3000)),
                ('banner_photo', models.ImageField(blank=True, default='post/def.jpg', null=True, upload_to='post/')),
                ('body_photo', models.ImageField(blank=True, null=True, upload_to='post/')),
                ('pub_date', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tasks.user_db')),
            ],
            options={
                'ordering': ['title'],
            },
        ),
    ]
