# Generated by Django 3.1.1 on 2021-01-16 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='super_plan_forms',
            name='historical_data',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
