# Generated by Django 3.1.1 on 2020-11-27 09:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='super_plan_forms',
            name='company_name',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='super_plan_forms',
            name='company_website_link',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='super_plan_forms',
            name='countrycode',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='super_plan_forms',
            name='email_id',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='super_plan_forms',
            name='gst_name',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='super_plan_forms',
            name='gst_number',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='super_plan_forms',
            name='owner_name',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='super_plan_forms',
            name='phone_number',
            field=models.CharField(max_length=13, null=True),
        ),
        migrations.AlterField(
            model_name='super_plan_forms',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tasks.user_db'),
        ),
    ]
