# Generated by Django 3.1.1 on 2021-02-20 10:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='super_plan_forms',
            name='projection_table',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projection_table', to='tasks.super_plan_projection'),
        ),
    ]
