# Generated by Django 3.1.1 on 2021-01-04 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='super_plan_forms',
            name='historicals_xl',
            field=models.ImageField(blank=True, null=True, upload_to='superplan-files/'),
        ),
    ]
