# Generated by Django 3.1.1 on 2020-12-12 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='super_plan_forms_multiple_images',
            name='i_6',
            field=models.ImageField(blank=True, null=True, upload_to='form_images/'),
        ),
    ]
