# Generated by Django 3.1.1 on 2021-02-23 16:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_auto_20210220_1605'),
    ]

    operations = [
        migrations.AddField(
            model_name='super_plan_projection',
            name='blnc_asset_turnover',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='blnc_asset_turnover', to='tasks.super_plan_forms_multiple_inputs'),
        ),
        migrations.AddField(
            model_name='super_plan_projection',
            name='blnc_average_interest_rate_debt',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='blnc_average_interest_rate_debt', to='tasks.super_plan_forms_multiple_inputs'),
        ),
        migrations.AddField(
            model_name='super_plan_projection',
            name='blnc_cash',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='blnc_cash', to='tasks.super_plan_forms_multiple_inputs'),
        ),
        migrations.AddField(
            model_name='super_plan_projection',
            name='blnc_check',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='blnc_check', to='tasks.super_plan_forms_multiple_inputs'),
        ),
        migrations.AddField(
            model_name='super_plan_projection',
            name='blnc_current_ratio',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='blnc_current_ratio', to='tasks.super_plan_forms_multiple_inputs'),
        ),
        migrations.AddField(
            model_name='super_plan_projection',
            name='blnc_debt_equity_ratiotimes',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='blnc_debt_equity_ratiotimes', to='tasks.super_plan_forms_multiple_inputs'),
        ),
        migrations.AddField(
            model_name='super_plan_projection',
            name='blnc_debt_to_total_funds',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='blnc_debt_to_total_funds', to='tasks.super_plan_forms_multiple_inputs'),
        ),
        migrations.AddField(
            model_name='super_plan_projection',
            name='blnc_deferred_tax_assets',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='blnc_deferred_tax_assets', to='tasks.super_plan_forms_multiple_inputs'),
        ),
        migrations.AddField(
            model_name='super_plan_projection',
            name='blnc_deferred_tax_liabilities',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='blnc_deferred_tax_liabilities', to='tasks.super_plan_forms_multiple_inputs'),
        ),
        migrations.AddField(
            model_name='super_plan_projection',
            name='blnc_equity_funds_raised',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='blnc_equity_funds_raised', to='tasks.super_plan_forms_multiple_inputs'),
        ),
        migrations.AddField(
            model_name='super_plan_projection',
            name='blnc_gross_fixed_assets',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='blnc_gross_fixed_assets', to='tasks.super_plan_forms_multiple_inputs'),
        ),
        migrations.AddField(
            model_name='super_plan_projection',
            name='blnc_intangible_assets_growth_or_amount',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='blnc_intangible_assets_growth_or_amount', to='tasks.super_plan_forms_multiple_inputs'),
        ),
        migrations.AddField(
            model_name='super_plan_projection',
            name='blnc_interest_expense',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='blnc_interest_expense', to='tasks.super_plan_forms_multiple_inputs'),
        ),
        migrations.AddField(
            model_name='super_plan_projection',
            name='blnc_inventory_no_of_days',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='blnc_inventory_no_of_days', to='tasks.super_plan_forms_multiple_inputs'),
        ),
        migrations.AddField(
            model_name='super_plan_projection',
            name='blnc_less_accumulated_depreciation',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='blnc_less_accumulated_depreciation', to='tasks.super_plan_forms_multiple_inputs'),
        ),
        migrations.AddField(
            model_name='super_plan_projection',
            name='blnc_long_term_investments_growth_or_amount',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='blnc_long_term_investments_growth_or_amount', to='tasks.super_plan_forms_multiple_inputs'),
        ),
        migrations.AddField(
            model_name='super_plan_projection',
            name='blnc_long_term_loans_and_advances_growth_or_amount',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='blnc_long_term_loans_and_advances_growth_or_amount', to='tasks.super_plan_forms_multiple_inputs'),
        ),
        migrations.AddField(
            model_name='super_plan_projection',
            name='blnc_long_term_provisions_growth_or_amount',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='blnc_long_term_provisions_growth_or_amount', to='tasks.super_plan_forms_multiple_inputs'),
        ),
        migrations.AddField(
            model_name='super_plan_projection',
            name='blnc_net_fixed_assets',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='blnc_net_fixed_assets', to='tasks.super_plan_forms_multiple_inputs'),
        ),
        migrations.AddField(
            model_name='super_plan_projection',
            name='blnc_other_current_assets_growth_or_amount',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='blnc_other_current_assets_growth_or_amount', to='tasks.super_plan_forms_multiple_inputs'),
        ),
        migrations.AddField(
            model_name='super_plan_projection',
            name='blnc_other_current_liabilities_growth_or_amount',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='blnc_other_current_liabilities_growth_or_amount', to='tasks.super_plan_forms_multiple_inputs'),
        ),
        migrations.AddField(
            model_name='super_plan_projection',
            name='blnc_other_non_current_assets_growth_or_amount',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='blnc_other_non_current_assets_growth_or_amount', to='tasks.super_plan_forms_multiple_inputs'),
        ),
        migrations.AddField(
            model_name='super_plan_projection',
            name='blnc_other_non_current_liabilities_growth_or_amount',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='blnc_other_non_current_liabilities_growth_or_amount', to='tasks.super_plan_forms_multiple_inputs'),
        ),
        migrations.AddField(
            model_name='super_plan_projection',
            name='blnc_quick_ratio',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='blnc_quick_ratio', to='tasks.super_plan_forms_multiple_inputs'),
        ),
        migrations.AddField(
            model_name='super_plan_projection',
            name='blnc_reserve_surplus',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='blnc_reserve_surplus', to='tasks.super_plan_forms_multiple_inputs'),
        ),
        migrations.AddField(
            model_name='super_plan_projection',
            name='blnc_return_on_equity',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='blnc_return_on_equity', to='tasks.super_plan_forms_multiple_inputs'),
        ),
        migrations.AddField(
            model_name='super_plan_projection',
            name='blnc_secured_loans_finance_lease_obligation',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='blnc_secured_loans_finance_lease_obligation', to='tasks.super_plan_forms_multiple_inputs'),
        ),
        migrations.AddField(
            model_name='super_plan_projection',
            name='blnc_secured_loans_from_banks',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='blnc_secured_loans_from_banks', to='tasks.super_plan_forms_multiple_inputs'),
        ),
        migrations.AddField(
            model_name='super_plan_projection',
            name='blnc_secured_loans_other_loans',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='blnc_secured_loans_other_loans', to='tasks.super_plan_forms_multiple_inputs'),
        ),
        migrations.AddField(
            model_name='super_plan_projection',
            name='blnc_secured_loans_term_loans',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='blnc_secured_loans_term_loans', to='tasks.super_plan_forms_multiple_inputs'),
        ),
        migrations.AddField(
            model_name='super_plan_projection',
            name='blnc_share_capital',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='blnc_share_capital', to='tasks.super_plan_forms_multiple_inputs'),
        ),
        migrations.AddField(
            model_name='super_plan_projection',
            name='blnc_short_term_borrowings_growth_or_amount',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='blnc_short_term_borrowings_growth_or_amount', to='tasks.super_plan_forms_multiple_inputs'),
        ),
        migrations.AddField(
            model_name='super_plan_projection',
            name='blnc_short_term_investments_growth_or_amount',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='blnc_short_term_investments_growth_or_amount', to='tasks.super_plan_forms_multiple_inputs'),
        ),
        migrations.AddField(
            model_name='super_plan_projection',
            name='blnc_short_term_loans_and_advances_growth_or_amount',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='blnc_short_term_loans_and_advances_growth_or_amount', to='tasks.super_plan_forms_multiple_inputs'),
        ),
        migrations.AddField(
            model_name='super_plan_projection',
            name='blnc_short_term_provisions_growth_or_amount',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='blnc_short_term_provisions_growth_or_amount', to='tasks.super_plan_forms_multiple_inputs'),
        ),
        migrations.AddField(
            model_name='super_plan_projection',
            name='blnc_sundry_creditors_no_of_days',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='blnc_sundry_creditors_no_of_days', to='tasks.super_plan_forms_multiple_inputs'),
        ),
        migrations.AddField(
            model_name='super_plan_projection',
            name='blnc_sundry_debtors_no_of_days',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='blnc_sundry_debtors_no_of_days', to='tasks.super_plan_forms_multiple_inputs'),
        ),
        migrations.AddField(
            model_name='super_plan_projection',
            name='blnc_total_assets_ab',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='blnc_total_assets_ab', to='tasks.super_plan_forms_multiple_inputs'),
        ),
        migrations.AddField(
            model_name='super_plan_projection',
            name='blnc_total_current_assets_b',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='blnc_total_current_assets_b', to='tasks.super_plan_forms_multiple_inputs'),
        ),
        migrations.AddField(
            model_name='super_plan_projection',
            name='blnc_total_current_liabilities_c',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='blnc_total_current_liabilities_c', to='tasks.super_plan_forms_multiple_inputs'),
        ),
        migrations.AddField(
            model_name='super_plan_projection',
            name='blnc_total_debt',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='blnc_total_debt', to='tasks.super_plan_forms_multiple_inputs'),
        ),
        migrations.AddField(
            model_name='super_plan_projection',
            name='blnc_total_liabilities_abc',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='blnc_total_liabilities_abc', to='tasks.super_plan_forms_multiple_inputs'),
        ),
        migrations.AddField(
            model_name='super_plan_projection',
            name='blnc_total_non_current_liabilities_b',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='blnc_total_non_current_liabilities_b', to='tasks.super_plan_forms_multiple_inputs'),
        ),
        migrations.AddField(
            model_name='super_plan_projection',
            name='blnc_total_noncurrent_asset_a',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='blnc_total_noncurrent_asset_a', to='tasks.super_plan_forms_multiple_inputs'),
        ),
        migrations.AddField(
            model_name='super_plan_projection',
            name='blnc_total_secured_loans',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='blnc_total_secured_loans', to='tasks.super_plan_forms_multiple_inputs'),
        ),
        migrations.AddField(
            model_name='super_plan_projection',
            name='blnc_total_shareholder_funds_a',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='blnc_total_shareholder_funds_a', to='tasks.super_plan_forms_multiple_inputs'),
        ),
        migrations.AddField(
            model_name='super_plan_projection',
            name='blnc_total_unsecured_loans',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='blnc_total_unsecured_loans', to='tasks.super_plan_forms_multiple_inputs'),
        ),
        migrations.AddField(
            model_name='super_plan_projection',
            name='blnc_unsecured_loans',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='blnc_unsecured_loans', to='tasks.super_plan_forms_multiple_inputs'),
        ),
    ]
