# Generated by Django 3.1.1 on 2020-12-24 13:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_auto_20201218_1157'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='super_plan_forms',
            name='depreciation_or_amount',
        ),
        migrations.RemoveField(
            model_name='super_plan_forms',
            name='ebitda',
        ),
        migrations.RemoveField(
            model_name='super_plan_forms',
            name='ebt',
        ),
        migrations.RemoveField(
            model_name='super_plan_forms',
            name='employee_cost',
        ),
        migrations.RemoveField(
            model_name='super_plan_forms',
            name='general_and_administration_cost',
        ),
        migrations.RemoveField(
            model_name='super_plan_forms',
            name='interest_expense_interest_or_amount',
        ),
        migrations.RemoveField(
            model_name='super_plan_forms',
            name='operating_expenses_growth_or_amount',
        ),
        migrations.RemoveField(
            model_name='super_plan_forms',
            name='other_expenses_growth_or_amount',
        ),
        migrations.RemoveField(
            model_name='super_plan_forms',
            name='pat',
        ),
        migrations.RemoveField(
            model_name='super_plan_forms',
            name='revenue_growth_or_amount',
        ),
        migrations.RemoveField(
            model_name='super_plan_forms',
            name='selling_and_marketing_cost',
        ),
        migrations.RemoveField(
            model_name='super_plan_forms',
            name='tax_expense_tax_or_amount',
        ),
        migrations.RemoveField(
            model_name='super_plan_forms',
            name='total_revenue_amount',
        ),
        migrations.AddField(
            model_name='super_plan_forms',
            name='administration_average_cost_per_employee',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='administration_average_cost_per_employee', to='tasks.super_plan_forms_multiple_inputs'),
        ),
        migrations.AddField(
            model_name='super_plan_forms',
            name='administration_no_of_employees',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='administration_no_of_employees', to='tasks.super_plan_forms_multiple_inputs'),
        ),
        migrations.AddField(
            model_name='super_plan_forms',
            name='advertisement',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='advertisement', to='tasks.super_plan_forms_multiple_inputs'),
        ),
        migrations.AddField(
            model_name='super_plan_forms',
            name='audit_fees',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_fees', to='tasks.super_plan_forms_multiple_inputs'),
        ),
        migrations.AddField(
            model_name='super_plan_forms',
            name='digital_marketing_cost',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='digital_marketing_cost', to='tasks.super_plan_forms_multiple_inputs'),
        ),
        migrations.AddField(
            model_name='super_plan_forms',
            name='direct_labour_average_cost_per_employee',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='direct_labour_average_cost_per_employee', to='tasks.super_plan_forms_multiple_inputs'),
        ),
        migrations.AddField(
            model_name='super_plan_forms',
            name='direct_labour_no_of_employees',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='direct_labour_no_of_employees', to='tasks.super_plan_forms_multiple_inputs'),
        ),
        migrations.AddField(
            model_name='super_plan_forms',
            name='direct_material_average_cost_per_unit',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='direct_material_average_cost_per_unit', to='tasks.super_plan_forms_multiple_inputs'),
        ),
        migrations.AddField(
            model_name='super_plan_forms',
            name='direct_material_units',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='direct_material_units', to='tasks.super_plan_forms_multiple_inputs'),
        ),
        migrations.AddField(
            model_name='super_plan_forms',
            name='electricity',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='electricity', to='tasks.super_plan_forms_multiple_inputs'),
        ),
        migrations.AddField(
            model_name='super_plan_forms',
            name='income_tax_rate',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='income_tax_rate', to='tasks.super_plan_forms_multiple_inputs'),
        ),
        migrations.AddField(
            model_name='super_plan_forms',
            name='logistics_expenses',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logistics_expenses', to='tasks.super_plan_forms_multiple_inputs'),
        ),
        migrations.AddField(
            model_name='super_plan_forms',
            name='marketing_average_cost_per_employee',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='marketing_average_cost_per_employee', to='tasks.super_plan_forms_multiple_inputs'),
        ),
        migrations.AddField(
            model_name='super_plan_forms',
            name='marketing_no_of_employees',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='marketing_no_of_employees', to='tasks.super_plan_forms_multiple_inputs'),
        ),
        migrations.AddField(
            model_name='super_plan_forms',
            name='other_administration_expenses_1',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='other_administration_expenses_1', to='tasks.super_plan_forms_multiple_inputs'),
        ),
        migrations.AddField(
            model_name='super_plan_forms',
            name='other_administration_expenses_2',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='other_administration_expenses_2', to='tasks.super_plan_forms_multiple_inputs'),
        ),
        migrations.AddField(
            model_name='super_plan_forms',
            name='other_administration_expenses_3',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='other_administration_expenses_3', to='tasks.super_plan_forms_multiple_inputs'),
        ),
        migrations.AddField(
            model_name='super_plan_forms',
            name='other_direct_expenses_1',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='other_direct_expenses_1', to='tasks.super_plan_forms_multiple_inputs'),
        ),
        migrations.AddField(
            model_name='super_plan_forms',
            name='other_direct_expenses_2',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='other_direct_expenses_2', to='tasks.super_plan_forms_multiple_inputs'),
        ),
        migrations.AddField(
            model_name='super_plan_forms',
            name='other_direct_expenses_3',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='other_direct_expenses_3', to='tasks.super_plan_forms_multiple_inputs'),
        ),
        migrations.AddField(
            model_name='super_plan_forms',
            name='other_employees_1',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='super_plan_forms',
            name='other_employees_1_average_cost_per_employee',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='other_employees_1_average_cost_per_employee', to='tasks.super_plan_forms_multiple_inputs'),
        ),
        migrations.AddField(
            model_name='super_plan_forms',
            name='other_employees_1_no_of_employees',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='other_employees_1_no_of_employees', to='tasks.super_plan_forms_multiple_inputs'),
        ),
        migrations.AddField(
            model_name='super_plan_forms',
            name='other_employees_2',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='super_plan_forms',
            name='other_employees_2_average_cost_per_employee',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='other_employees_2_average_cost_per_employee', to='tasks.super_plan_forms_multiple_inputs'),
        ),
        migrations.AddField(
            model_name='super_plan_forms',
            name='other_employees_2_no_of_employees',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='other_employees_2_no_of_employees', to='tasks.super_plan_forms_multiple_inputs'),
        ),
        migrations.AddField(
            model_name='super_plan_forms',
            name='other_employees_3',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='super_plan_forms',
            name='other_employees_3_average_cost_per_employee',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='other_employees_3_average_cost_per_employee', to='tasks.super_plan_forms_multiple_inputs'),
        ),
        migrations.AddField(
            model_name='super_plan_forms',
            name='other_employees_3_no_of_employees',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='other_employees_3_no_of_employees', to='tasks.super_plan_forms_multiple_inputs'),
        ),
        migrations.AddField(
            model_name='super_plan_forms',
            name='other_expenses_1',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='other_expenses_1', to='tasks.super_plan_forms_multiple_inputs'),
        ),
        migrations.AddField(
            model_name='super_plan_forms',
            name='other_expenses_2',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='other_expenses_2', to='tasks.super_plan_forms_multiple_inputs'),
        ),
        migrations.AddField(
            model_name='super_plan_forms',
            name='other_income_growth_or',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='super_plan_forms',
            name='other_selling_and_marketing_expenses_1',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='other_selling_and_marketing_expenses_1', to='tasks.super_plan_forms_multiple_inputs'),
        ),
        migrations.AddField(
            model_name='super_plan_forms',
            name='other_selling_and_marketing_expenses_2',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='other_selling_and_marketing_expenses_2', to='tasks.super_plan_forms_multiple_inputs'),
        ),
        migrations.AddField(
            model_name='super_plan_forms',
            name='other_selling_and_marketing_expenses_3',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='other_selling_and_marketing_expenses_3', to='tasks.super_plan_forms_multiple_inputs'),
        ),
        migrations.AddField(
            model_name='super_plan_forms',
            name='printing_and_stationery',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='printing_and_stationery', to='tasks.super_plan_forms_multiple_inputs'),
        ),
        migrations.AddField(
            model_name='super_plan_forms',
            name='realised_foreign_exchange_gain_or',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='super_plan_forms',
            name='realised_foreign_exchange_gain_or_loss',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='realised_foreign_exchange_gain_or_loss', to='tasks.super_plan_forms_multiple_inputs'),
        ),
        migrations.AddField(
            model_name='super_plan_forms',
            name='rent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rent', to='tasks.super_plan_forms_multiple_inputs'),
        ),
        migrations.AddField(
            model_name='super_plan_forms',
            name='research_and_development_average_cost_per_employee',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='research_and_development_average_cost_per_employee', to='tasks.super_plan_forms_multiple_inputs'),
        ),
        migrations.AddField(
            model_name='super_plan_forms',
            name='research_and_development_no_of_employees',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='research_and_development_no_of_employees', to='tasks.super_plan_forms_multiple_inputs'),
        ),
        migrations.AddField(
            model_name='super_plan_forms',
            name='revenue_growth_1_or',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='super_plan_forms',
            name='revenue_growth_2_or',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='super_plan_forms',
            name='revenue_growth_3_or',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='super_plan_forms',
            name='revenue_growth_4_or',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='super_plan_forms',
            name='revenue_growth_or_amount_1',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='revenue_growth_or_amount_1', to='tasks.super_plan_forms_multiple_inputs'),
        ),
        migrations.AddField(
            model_name='super_plan_forms',
            name='revenue_growth_or_amount_2',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='revenue_growth_or_amount_2', to='tasks.super_plan_forms_multiple_inputs'),
        ),
        migrations.AddField(
            model_name='super_plan_forms',
            name='revenue_growth_or_amount_3',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='revenue_growth_or_amount_3', to='tasks.super_plan_forms_multiple_inputs'),
        ),
        migrations.AddField(
            model_name='super_plan_forms',
            name='revenue_growth_or_amount_4',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='revenue_growth_or_amount_4', to='tasks.super_plan_forms_multiple_inputs'),
        ),
        migrations.AddField(
            model_name='super_plan_forms',
            name='sales_commissions',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales_commissions', to='tasks.super_plan_forms_multiple_inputs'),
        ),
        migrations.AddField(
            model_name='super_plan_forms',
            name='selling_and_distribution_average_cost_per_employee',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='selling_and_distribution_average_cost_per_employee', to='tasks.super_plan_forms_multiple_inputs'),
        ),
        migrations.AddField(
            model_name='super_plan_forms',
            name='selling_and_distribution_no_of_employees',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='selling_and_distribution_no_of_employees', to='tasks.super_plan_forms_multiple_inputs'),
        ),
        migrations.AddField(
            model_name='super_plan_forms',
            name='telephone_expenses',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='telephone_expenses', to='tasks.super_plan_forms_multiple_inputs'),
        ),
        migrations.AddField(
            model_name='super_plan_forms',
            name='travelling_expenses',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='travelling_expenses', to='tasks.super_plan_forms_multiple_inputs'),
        ),
    ]
