# Generated by Django 3.1.1 on 2020-11-17 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_auto_20201117_1958'),
    ]

    operations = [
        migrations.AddField(
            model_name='super_plan_forms',
            name='current_fillup_position',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.DeleteModel(
            name='user_current_super_plan_forms',
        ),
    ]
