# Generated by Django 3.1.1 on 2020-09-17 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_posts'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banners',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('desc', models.CharField(max_length=500, null=True)),
                ('alt', models.CharField(default='banner image', max_length=100)),
                ('category', models.CharField(default='uncategorized', max_length=100)),
                ('photo', models.ImageField(upload_to='banner/')),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Pages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('meta', models.CharField(max_length=500)),
                ('slug', models.CharField(max_length=500)),
                ('keywords', models.CharField(max_length=300)),
                ('post', models.CharField(max_length=3000)),
                ('body_photo', models.ImageField(blank=True, null=True, upload_to='page/')),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
