# Generated by Django 3.1.1 on 2021-01-04 02:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_super_plan_forms_historicals_xl'),
    ]

    operations = [
        migrations.RenameField(
            model_name='super_plan_forms',
            old_name='historicals_xl',
            new_name='historical_xl',
        ),
    ]
