# Generated by Django 3.1.1 on 2021-02-28 08:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_auto_20210223_2217'),
    ]

    operations = [
        migrations.AddField(
            model_name='super_plan_projection',
            name='csf_balancing_figure',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='csf_balancing_figure', to='tasks.super_plan_forms_multiple_inputs'),
        ),
        migrations.AddField(
            model_name='super_plan_projection',
            name='csf_capital_expenditure',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='csf_capital_expenditure', to='tasks.super_plan_forms_multiple_inputs'),
        ),
        migrations.AddField(
            model_name='super_plan_projection',
            name='csf_cash_and_cash_equivalents_at_the_beginning_of_the_year',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='csf_cash_and_cash_equivalents_at_the_beginning_of_the_year', to='tasks.super_plan_forms_multiple_inputs'),
        ),
        migrations.AddField(
            model_name='super_plan_projection',
            name='csf_cash_and_cash_equivalents_at_the_end_of_the_year',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='csf_cash_and_cash_equivalents_at_the_end_of_the_year', to='tasks.super_plan_forms_multiple_inputs'),
        ),
        migrations.AddField(
            model_name='super_plan_projection',
            name='csf_decrease_increase_in_current_liabilities_and_provisions',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='csf_decrease_increase_in_current_liabilities_and_provisions', to='tasks.super_plan_forms_multiple_inputs'),
        ),
        migrations.AddField(
            model_name='super_plan_projection',
            name='csf_decrease_increase_in_inventories',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='csf_decrease_increase_in_inventories', to='tasks.super_plan_forms_multiple_inputs'),
        ),
        migrations.AddField(
            model_name='super_plan_projection',
            name='csf_decrease_increase_in_other_current_assets',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='csf_decrease_increase_in_other_current_assets', to='tasks.super_plan_forms_multiple_inputs'),
        ),
        migrations.AddField(
            model_name='super_plan_projection',
            name='csf_decrease_increase_in_sundry_debtors',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='csf_decrease_increase_in_sundry_debtors', to='tasks.super_plan_forms_multiple_inputs'),
        ),
        migrations.AddField(
            model_name='super_plan_projection',
            name='csf_ebitda',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='csf_ebitda', to='tasks.super_plan_forms_multiple_inputs'),
        ),
        migrations.AddField(
            model_name='super_plan_projection',
            name='csf_effect_of_exchange_differences_on_translation_of_foreign_currency_cash_and_cash_equivalents',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='csf_effect_of_exchange_differences_on_translation_of_foreign_currency_cash_and_cash_equivalents', to='tasks.super_plan_forms_multiple_inputs'),
        ),
        migrations.AddField(
            model_name='super_plan_projection',
            name='csf_equity_funds_raised',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='csf_equity_funds_raised', to='tasks.super_plan_forms_multiple_inputs'),
        ),
        migrations.AddField(
            model_name='super_plan_projection',
            name='csf_free_cash_flow',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='csf_free_cash_flow', to='tasks.super_plan_forms_multiple_inputs'),
        ),
        migrations.AddField(
            model_name='super_plan_projection',
            name='csf_free_cash_flow_operating_cash_flow',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='csf_free_cash_flow_operating_cash_flow', to='tasks.super_plan_forms_multiple_inputs'),
        ),
        migrations.AddField(
            model_name='super_plan_projection',
            name='csf_income_taxes_paid',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='csf_income_taxes_paid', to='tasks.super_plan_forms_multiple_inputs'),
        ),
        migrations.AddField(
            model_name='super_plan_projection',
            name='csf_intangible_assets',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='csf_intangible_assets', to='tasks.super_plan_forms_multiple_inputs'),
        ),
        migrations.AddField(
            model_name='super_plan_projection',
            name='csf_interest_paid_on_loans',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='csf_interest_paid_on_loans', to='tasks.super_plan_forms_multiple_inputs'),
        ),
        migrations.AddField(
            model_name='super_plan_projection',
            name='csf_issue_of_share_capital_net_of_issue_expenses_paid',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='csf_issue_of_share_capital_net_of_issue_expenses_paid', to='tasks.super_plan_forms_multiple_inputs'),
        ),
        migrations.AddField(
            model_name='super_plan_projection',
            name='csf_loss_profit_on_sale_of_fixed_assets',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='csf_loss_profit_on_sale_of_fixed_assets', to='tasks.super_plan_forms_multiple_inputs'),
        ),
        migrations.AddField(
            model_name='super_plan_projection',
            name='csf_net_cash_provided_by_used_in_operating_activities',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='csf_net_cash_provided_by_used_in_operating_activities', to='tasks.super_plan_forms_multiple_inputs'),
        ),
        migrations.AddField(
            model_name='super_plan_projection',
            name='csf_net_cash_provided_used_by_financing_activities',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='csf_net_cash_provided_used_by_financing_activities', to='tasks.super_plan_forms_multiple_inputs'),
        ),
        migrations.AddField(
            model_name='super_plan_projection',
            name='csf_net_cash_provided_used_in_investing_activities',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='csf_net_cash_provided_used_in_investing_activities', to='tasks.super_plan_forms_multiple_inputs'),
        ),
        migrations.AddField(
            model_name='super_plan_projection',
            name='csf_net_increase_decrease_in_cash_and_cash_equivalents',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='csf_net_increase_decrease_in_cash_and_cash_equivalents', to='tasks.super_plan_forms_multiple_inputs'),
        ),
        migrations.AddField(
            model_name='super_plan_projection',
            name='csf_operating_cash_flow',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='csf_operating_cash_flow', to='tasks.super_plan_forms_multiple_inputs'),
        ),
        migrations.AddField(
            model_name='super_plan_projection',
            name='csf_operating_cash_flow_sales',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='csf_operating_cash_flow_sales', to='tasks.super_plan_forms_multiple_inputs'),
        ),
        migrations.AddField(
            model_name='super_plan_projection',
            name='csf_operating_profit_before_working_capital_changes',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='csf_operating_profit_before_working_capital_changes', to='tasks.super_plan_forms_multiple_inputs'),
        ),
        migrations.AddField(
            model_name='super_plan_projection',
            name='csf_other_income',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='csf_other_income', to='tasks.super_plan_forms_multiple_inputs'),
        ),
        migrations.AddField(
            model_name='super_plan_projection',
            name='csf_proceeds_repayment_of_loans',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='csf_proceeds_repayment_of_loans', to='tasks.super_plan_forms_multiple_inputs'),
        ),
        migrations.AddField(
            model_name='super_plan_projection',
            name='csf_purchase_of_fixed_assets',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='csf_purchase_of_fixed_assets', to='tasks.super_plan_forms_multiple_inputs'),
        ),
        migrations.AddField(
            model_name='super_plan_projection',
            name='csf_realised_foreign_exchange_gain_loss',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='csf_realised_foreign_exchange_gain_loss', to='tasks.super_plan_forms_multiple_inputs'),
        ),
    ]
