# Generated by Django 3.1.1 on 2021-01-04 02:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_auto_20210104_0809'),
    ]

    operations = [
        migrations.AddField(
            model_name='super_plan_forms',
            name='capex_opening_gross',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='capex_opening_gross', to='tasks.super_plan_forms_multiple_inputs'),
        ),
    ]
