# Generated by Django 3.1.1 on 2020-11-28 09:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_auto_20201127_1551'),
    ]

    operations = [
        migrations.AlterField(
            model_name='super_plan_forms',
            name='depreciation_or_amount',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='depreciation_or_amount', to='tasks.super_plan_forms_multiple_inputs'),
        ),
        migrations.AlterField(
            model_name='super_plan_forms',
            name='ebitda',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ebitda', to='tasks.super_plan_forms_multiple_inputs'),
        ),
        migrations.AlterField(
            model_name='super_plan_forms',
            name='ebt',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ebt', to='tasks.super_plan_forms_multiple_inputs'),
        ),
        migrations.AlterField(
            model_name='super_plan_forms',
            name='employee_cost',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employee_cost', to='tasks.super_plan_forms_multiple_inputs'),
        ),
        migrations.AlterField(
            model_name='super_plan_forms',
            name='general_and_administration_cost',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='general_and_administration_cost', to='tasks.super_plan_forms_multiple_inputs'),
        ),
        migrations.AlterField(
            model_name='super_plan_forms',
            name='interest_expense_interest_or_amount',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='interest_expense_interest_or_amount', to='tasks.super_plan_forms_multiple_inputs'),
        ),
        migrations.AlterField(
            model_name='super_plan_forms',
            name='operating_expenses_growth_or_amount',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='operating_expenses_growth_or_amount', to='tasks.super_plan_forms_multiple_inputs'),
        ),
        migrations.AlterField(
            model_name='super_plan_forms',
            name='other_expenses_growth_or_amount',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='other_expenses_growth_or_amount', to='tasks.super_plan_forms_multiple_inputs'),
        ),
        migrations.AlterField(
            model_name='super_plan_forms',
            name='other_income_growth_or_amount',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='other_income_growth_or_amount', to='tasks.super_plan_forms_multiple_inputs'),
        ),
        migrations.AlterField(
            model_name='super_plan_forms',
            name='pat',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pat', to='tasks.super_plan_forms_multiple_inputs'),
        ),
        migrations.AlterField(
            model_name='super_plan_forms',
            name='revenue_growth_or_amount',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='revenue_growth_or_amount', to='tasks.super_plan_forms_multiple_inputs'),
        ),
        migrations.AlterField(
            model_name='super_plan_forms',
            name='selling_and_marketing_cost',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='selling_and_marketing_cost', to='tasks.super_plan_forms_multiple_inputs'),
        ),
        migrations.AlterField(
            model_name='super_plan_forms',
            name='tax_expense_tax_or_amount',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tax_expense_tax_or_amount', to='tasks.super_plan_forms_multiple_inputs'),
        ),
        migrations.AlterField(
            model_name='super_plan_forms',
            name='total_revenue_amount',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='total_revenue_amount', to='tasks.super_plan_forms_multiple_inputs'),
        ),
    ]
