# Generated by Django 3.1.1 on 2020-11-17 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_auto_20201117_2037'),
    ]

    operations = [
        migrations.AlterField(
            model_name='super_plan_forms',
            name='current_fillup_position',
            field=models.IntegerField(null=True),
        ),
    ]
