# Generated by Django 3.1.1 on 2020-11-18 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_auto_20201117_2053'),
    ]

    operations = [
        migrations.AddField(
            model_name='super_plan_forms',
            name='countrycode',
            field=models.CharField(default=91, max_length=10),
            preserve_default=False,
        ),
    ]
