# Generated by Django 3.1.1 on 2021-01-04 04:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_super_plan_forms_capex_opening_gross'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='super_plan_forms',
            name='operating_expenses_growth_or_amount_years',
        ),
        migrations.RemoveField(
            model_name='super_plan_forms',
            name='revenue_growth_or_amount_years',
        ),
        migrations.AddField(
            model_name='super_plan_forms',
            name='profit_and_loss_years',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='profit_and_loss_years', to='tasks.super_plan_forms_multiple_inputs'),
        ),
    ]
