# Generated by Django 3.1.1 on 2021-01-04 04:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0005_auto_20210104_0933'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='super_plan_forms',
            name='current_assets_years',
        ),
        migrations.RemoveField(
            model_name='super_plan_forms',
            name='current_liabilities_years',
        ),
        migrations.RemoveField(
            model_name='super_plan_forms',
            name='non_current_assets_years',
        ),
        migrations.RemoveField(
            model_name='super_plan_forms',
            name='non_current_liabilities_years',
        ),
        migrations.RemoveField(
            model_name='super_plan_forms',
            name='share_capital_years',
        ),
        migrations.AddField(
            model_name='super_plan_forms',
            name='balance_sheet_years',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='balance_sheet_years', to='tasks.super_plan_forms_multiple_inputs'),
        ),
    ]
