# Generated by Django 3.1.1 on 2021-03-07 14:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0005_super_plan_forms_multiple_inputs_xl_f_6'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='super_plan_forms_multiple_inputs_xl',
            name='f_4',
        ),
        migrations.RemoveField(
            model_name='super_plan_forms_multiple_inputs_xl',
            name='f_5',
        ),
        migrations.RemoveField(
            model_name='super_plan_forms_multiple_inputs_xl',
            name='f_6',
        ),
    ]
