# Generated by Django 3.1.1 on 2021-02-03 11:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0005_auto_20210203_1629'),
    ]

    operations = [
        migrations.AddField(
            model_name='super_plan_forms',
            name='projection_tabl',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='tasks.super_plan_projection'),
        ),
        migrations.AlterField(
            model_name='super_plan_projection',
            name='form_id',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
