# Generated by Django 3.1.1 on 2021-01-08 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0007_auto_20210104_2223'),
    ]

    operations = [
        migrations.AlterField(
            model_name='super_plan_forms',
            name='industry_type',
            field=models.IntegerField(null=True),
        ),
    ]
