# Generated by Django 3.1.1 on 2021-01-08 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0008_auto_20210108_1557'),
    ]

    operations = [
        migrations.AddField(
            model_name='super_plan_forms',
            name='industry_analysis_img',
            field=models.ImageField(blank=True, null=True, upload_to='superplan-files/'),
        ),
    ]
