# Generated by Django 3.1.1 on 2021-01-12 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0009_super_plan_forms_industry_analysis_img'),
    ]

    operations = [
        migrations.RenameField(
            model_name='super_plan_forms',
            old_name='industry_analysis',
            new_name='industry_analysis_glob',
        ),
        migrations.RenameField(
            model_name='super_plan_forms',
            old_name='industry_analysis_img',
            new_name='industry_analysis_glob_img',
        ),
        migrations.AddField(
            model_name='super_plan_forms',
            name='industry_analysis_india',
            field=models.CharField(max_length=8000, null=True),
        ),
        migrations.AddField(
            model_name='super_plan_forms',
            name='industry_analysis_india_img',
            field=models.ImageField(blank=True, null=True, upload_to='superplan-files/'),
        ),
    ]
