# Generated by Django 3.1.1 on 2021-01-05 10:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0007_auto_20210104_2223'),
        ('business_management', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='industries',
            name='address',
        ),
        migrations.RemoveField(
            model_name='industries',
            name='email',
        ),
        migrations.RemoveField(
            model_name='industries',
            name='mobile',
        ),
        migrations.RemoveField(
            model_name='industries',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='industries',
            name='photo',
        ),
        migrations.CreateModel(
            name='Industry_growth_drivers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('drivers', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='drivers', to='tasks.super_plan_forms_multiple_inputs')),
                ('industry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='business_management.industries')),
            ],
        ),
        migrations.CreateModel(
            name='Industry_analysis',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('india', models.CharField(max_length=3000)),
                ('india_img', models.ImageField(blank=True, null=True, upload_to='industry/')),
                ('glob', models.CharField(max_length=3000)),
                ('glob_img', models.ImageField(blank=True, null=True, upload_to='industry/')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('industry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='business_management.industries')),
            ],
        ),
    ]
