# Generated by Django 3.1.1 on 2021-01-06 10:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0007_auto_20210104_2223'),
        ('business_management', '0002_auto_20210105_1625'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='industry_growth_drivers',
            name='drivers',
        ),
        migrations.AddField(
            model_name='industry_growth_drivers',
            name='drivers_c',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='drivers_c', to='tasks.super_plan_forms_multiple_inputs'),
        ),
        migrations.AddField(
            model_name='industry_growth_drivers',
            name='drivers_t',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='drivers_t', to='tasks.super_plan_forms_multiple_inputs'),
        ),
    ]
