# Generated by Django 3.1.1 on 2020-09-23 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business_management', '0002_packs_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='packs',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='package/'),
        ),
    ]
