# Generated by Django 3.1.1 on 2020-09-24 13:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
        ('business_management', '0003_auto_20200923_2003'),
    ]

    operations = [
        migrations.CreateModel(
            name='Templates',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('code', models.CharField(max_length=50)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('ind', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='business_management.industries')),
                ('pack', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='business_management.packs')),
            ],
        ),
        migrations.CreateModel(
            name='User_bookings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='business_management.templates')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tasks.user_db')),
            ],
        ),
    ]
